/*********** Generated by reswrap version 5.2.0 *********/

/* Created by reswrap from file Icon.gif */
extern const unsigned char Icon[];

/* Created by reswrap from file MiniIcon.ico */
extern const unsigned char MiniIcon[];
