#ifndef _PROTOCOLS_H_
#define _PROTOCOLS_H_

#define IRMP_N_PROTOCOLS                        62              // number of supported protocols

cString protocols[IRMP_N_PROTOCOLS + 1] = {
"unknown",
"SIRCS: Sony",
"NEC: NEC, Pioneer, JVC, Toshiba, NoName etc.",
"Samsung",
"Matsushita",
"Kaseikyo (Panasonic etc)",
"RECS80: Philips, Thomson, Nordmende, Telefunken, Saba",
"RC5: Philips etc",
"Denon, Sharp",
"RC6: Philips etc",
"Samsung32",
"Apple",
"RECS80EXT: Philips, Technisat, Thomson, Nordmende, Telefunken, Saba",
"Nubert",
"Bang & Olufsen",
"Grundig",
"Nokia",
"Siemens, e.g. Gigaset",
"FDC keyboard",
"RC Car",
"JVC",
"RC6A: e.g. Kathrein, XBOX",
"Nikon",
"Ruwido, e.g. T-Home Mediareceiver",
"IR60 (SDA2008)",
"Kathrein",
"Netbox keyboard",
"NEC16: NEC with 16 bits (incl. sync)",
"NEC42: NEC with 42 bits",
"LEGO Power Functions RC",
"Thomson",
"BOSE",
"A1 TV Box",
"ORTEK - Hama",
"Telefunken (1560)",
"iRobot Roomba vacuum cleaner",
"RCMM32: Fujitsu-Siemens (Activy remote control)",
"RCMM24: Fujitsu-Siemens (Activy keyboard)",
"RCMM12: Fujitsu-Siemens (Activy keyboard)",
"SPEAKER: Another loudspeaker protocol, similar to Nubert",
"LG air conditioner",
"SAMSUNG48: air conditioner with SAMSUNG protocol (48 bits)",
"Merlin (Pollin 620 185)",
"Pentax camera",
"FAN (ventilator), very similar to NUBERT",
"S100: very similar to RC5",
"ACP24: Stiebel Eltron ACP24 air conditioner",
"Technics, similar to Matsushita",
"Panasonic (Beamer)",
"Mitsubishi-Heavy Aircondition",
"Vincent",
"SAMSUNG AH",
"IRMP16: IRMP specific protocol for data transfer, e.g. between two microcontrollers via IR",
"Gree climate",
"RC II Infra Red Remote Control Protocol for FM8",
"METZ",
"ONKYO",
"RF Generic, 24 Bits (Pollin 550666, EAN 4049702006022 and many other similar RF remote controls))",
"RF PC X10 Remote Control (Medion, Pollin 721815)",
"RF PC Medion Remote Control (Medion)",
"MELINERA",
"RC6A20 e.g. Sky+",
"RC6A28 e.g. Sky Q (Sky+ Pro)",
};

#endif // _PROTOCOLS_H_
